### ISSUE TITLE
Seems to open the same file a lot

### ISSUE THREAD

**Issue by haakonnessjoen** [andrewshell/node-fs-key-value#1]
Hi,

I do something along the lines of:

```
var mydb = new FsKeyValue('./data', function (err, db) {
        // blabla
        db.get('teams', function (err, data) {
                setInterval(function () {
                        db.put('teams', teams, function (err) {
                                if (err) {
                                        console.log("Error saving data:", err);
                                }
                        });
                }, 10000);
        });
});
```

But this seems to open the same file over and over again, without closing it.

After a while, I get a lot of [Error: EMFILE, open 'data/teams'] errno: 20, code: 'EMFILE'.

Which suggests that too many files are open. Though it's probably just the same file opened over and over again.

**Comment by andrewshell** [comment]
I took a look at the code and the only files that could keep getting opened were the lock files.  So I cleaned up the code and made sure all the lock files were closed after being unlocked.  Let me know if this resolves your issue.
